#!/bin/bash
condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_ttbarToBsToTauTau_RunIIUL18_nanoAODv15_v1_0000_ee.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_ttbarToBsToTauTau_RunIIUL18_nanoAODv15_v1_0000_mumu.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_ttbarToBsToTauTau_RunIIUL18_nanoAODv15_v1_0000_e.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_ttbarToBsToTauTau_RunIIUL18_nanoAODv15_v1_0000_mu.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTTo2L2Nu_RunIIUL18_nanoAODv15_v1_0000_ee.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTTo2L2Nu_RunIIUL18_nanoAODv15_v1_0000_mumu.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTTo2L2Nu_RunIIUL18_nanoAODv15_v1_0000_e.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTTo2L2Nu_RunIIUL18_nanoAODv15_v1_0000_mu.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTToSemiLeptonic_RunIIUL18_nanoAODv15_0000_ee.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTToSemiLeptonic_RunIIUL18_nanoAODv15_0000_mumu.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTToSemiLeptonic_RunIIUL18_nanoAODv15_0000_e.sub

condor_submit /afs/cern.ch/work/c/cbasile/BsTauTau_ttbar/flattuplizer/CMSSW_15_0_18/src/BsTauTauAnalyzer/Flattener/scripts/FarmLocalNtuple_2018_UParTedge-ext/condor_generator_TTToSemiLeptonic_RunIIUL18_nanoAODv15_0000_mu.sub

echo "DONE | all jobs submitted"
